#!/bin/sh

f_cell_activate() {
	ifconfig umb0 apn broadband class LTE up
	sleep 1
}

f_cell_status() {
	_cell_status=""
	_cell_status=`ifconfig umb0 | grep status | awk '{ print $2 }'`
	if [ "$_cell_status" == "active" ]; then
		cell_status=0
	else
		cell_status=1
	fi
	return $cell_status
}

f_set_route() {
	cell_route=`ifconfig umb0 | grep inet | awk '{ print $2 }'`
	route add -ifp umb0 default ${cell_route}
	if [ $? == 0 ]; then
		echo "Default route added"
	else
		echo "Default route failure"
	fi
}

f_set_dns() {
	cell_dns=`ifconfig umb0 | grep dns | awk '{ print $2 }'`
	if [ "$cell_dns" == "" ]; then
		echo "Failure"
	else
		echo "nameserver ${cell_dns}" > /etc/resolv.conf
		echo "lookup file bind" >> /etc/resolv.conf
	fi
}

f_cell_activate
check=1
while [ $check -eq 1 ]
do
	sleep 1
	f_cell_status
	if [ $? == 0 ]; then
		f_set_route
		f_set_dns
		break
	fi
done
