#!/bin/sh

f_cell_activate() {
	ifconfig umb0 class LTE apn broadband up
	sleep 1
}

f_cell_status() {
	_CELL_STATUS=""
	_CELL_STATUS=`ifconfig umb0 | grep status | awk '{ print $2 }'`
	if [ "${_CELL_STATUS}" == "active" ]; then
		CELL_STATUS=0
	else
		CELL_STATUS=1
	fi
	return ${CELL_STATUS}
}

f_set_route() {
	CELL_ROUTE=`ifconfig umb0 | grep inet | awk '{ print $2 }'`
	route add -ifp umb0 default ${CELL_ROUTE}
	if [ $? == 0 ]; then
		echo "Default route added"
	else
		echo "Default route failure"
	fi
}

f_set_dns() {
	CELL_DNS=`ifconfig umb0 | grep dns | awk '{ print $2 }'`
	if [ "${CELL_DNS}" == "" ]; then
		echo "Failure"
	else
		echo "nameserver ${CELL_DNS}" > /etc/resolv.conf
		echo "lookup file bind" >> /etc/resolv.conf
	fi
}

f_cell_activate
while true ; do
	f_cell_status
	if [ $? == 0 ]; then
		f_set_route
		f_set_dns
		break
	fi
done
